[gcp_service_account]
type = "service_account"
project_id = "grantfinderai-463413"
private_key_id = "c8586c3466a7bd46ebf8e4418f7395961cb0d5a3"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIE...\\n-----END PRIVATE KEY-----\\n"
client_email = "grantfinder-agent@grantfinderai-463413.iam.gserviceaccount.com"
client_id = "117264351927186793521"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/grantfinder-agent@grantfinderai-463413.iam.gserviceaccount.com"

gmail_app_password = "gfzr sxaf cksn evbg"
