[gcp_service_account]
type = "service_account"
project_id = "grantfinderai-463413"
private_key_id = "c8586c3466a7bd46ebf8e4418f7395961cb0d5a3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6lwCPNnZuENB7
w7gRkOKFitVaJAHIQPsTE4PieFeKfXrUHXM+2emEYiCwkhxtU7NCJYbHMquovNii
piK3KY3aNK94MNZs3S57+laIz/ndeLrvJ26Eo5TVsTXwHTx6ylTkNa7cCeTsGxZ8
qZkxnj+Ey4kz4nfj4+LRiz1O890IIByb4kKLYh6toMaVt+uR2+3C8oNqJK4xI6Wl
PjblCHhtO/6YFqSngaajJbiap8cOIcrz0grg7/jcrTm+D0C9k1/j48YHfJa6vI7M
1ntmm9KnOGREPd2YFracAZIWvrv3PhWS8fB8PTWWlCZ1mB2nsmhJDR/76PNkzEou
kF3BfezjAgMBAAECggEABN49H6P7+r0p2i6AVjPYgIzfc0bA7t1Nb6gei3g4mHn4
MNjWti/LRuWkgrJBxQonSmwVFELRdbch5ha9jWoZIX64+B46pV+dEdxsUmib1UXV
Pic9pREgFfYMpuxjNNl/aBMfDYCdJ2NBiRSHsIdJt4iGMgNZT/wUz0wwjt5ZEc8D
hdi1zs1/P4Vp/HBIVorB+1mtt7dAZMmrv5Xdc/o742HT+K/PzVymTSGJ47MhLT/e
0iWq1fXqFVwPUwC9HPqwYf7yNunvRi42t8SqnbUA1ptIyQ0gNPO2Zb5//gYtjrrA
5tsKEazAn8fepD9gaTIfxJhACFwJJgIY9kNVXbmfEQKBgQDqhS1K6bTRA8ZR6DnG
/nmDSooxLMr1ff/7epOkcW8/tOG5I58o5DtFJmBQK6gVtv+WyZYuTaZTnND2J8b9
h2Qp5WFM/1EzenMA+wCoWfw0rVFJRcU9ZAU9gIlmTkQ+OE3o9cWu1o0EWq7eOpdQ
u66K2GPrQXCBwxbY53kLv83KmQKBgQDLrf8LgqOmRg/faE2fzNzUdLyaftNXjAKK
AKyZJfvB69WsXSoMN3nDi0vq7rULLgoAs4+fM/mJ5Sw4F4uj/pUSxYYkOcpBYDCx
u9q6obzRAOvWepo7PNQJF1Bii4RUEscT7QZ5XVCKYyfCQZaM4mVLoibFHfW/albz
wh3mPfv82wKBgHANO6vMaFFpnUsrStfSZJqfddGzFjIfhrxQP9TVQhNNSIBeDcDK
86rBgEkt4rylWA9it/fdr/fJOGo0bTZbhzchWtEgOFsBSYuRYioN/Jvqp6j7xhbk
AED3di7EfITCAC+rpk04Q95tuZmCoyO22NmMNImGFcxaO0NdrY84kIoZAoGAVgaH
UjU7KV8uFQ3Yu0Wrf5BOmHI4kSFxcRgXzhdc3erdtI8k00QbCZwr1G49yRsI3oL4
hiVNoBBLPOW09O7xx5vlrCc8ZaBa8LaHC4yEU0IwWcYunhZy9+QA7549pcTIkIHr
2havjcOTZ1iMXbTBU9CIz3h38wDW+N1kA3rqk0ECgYAyostns+rhZ6PyXIgz6doH
lvtTFtCuRjXnwE6B0Yb6KXtgMloG8WVdmOg0+q5OHbi+MWfYtC9dCLfLYInbTqWp
hbAsTeZDGNrJIz7rTCPZZoIz1V7HQj63pcVy2BN7LSnPDvauNAeHITNFmx7KFRWI
jV0+yOXdbgx7EnW/8tlCYg==
-----END PRIVATE KEY-----"""
client_email = "grantfinder-agent@grantfinderai-463413.iam.gserviceaccount.com"
client_id = "117264351927186793521"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/grantfinder-agent@grantfinderai-463413.iam.gserviceaccount.com"

gmail_app_password = "gfzr sxaf cksn evbg"
